begin;
create table public.preventive_guidance_sources (
 id uuid primary key default gen_random_uuid(),source_key text unique not null check(source_key ~ '^[a-z0-9_]{1,100}$'),publisher text not null check(length(publisher) between 1 and 160),title text not null check(length(title) between 1 and 250),source_url text not null check(length(source_url)<=2048 and source_url ~ '^https://'),publication_year integer check(publication_year between 1900 and 2200),reviewed_at timestamptz not null check(isfinite(reviewed_at)),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.preventive_guidance_rules (
 id uuid primary key default gen_random_uuid(),rule_key text unique not null check(rule_key ~ '^[a-z0-9_]{1,100}$'),source_id uuid not null references public.preventive_guidance_sources(id),species text not null check(species in ('dog','cat')),category text not null check(category in ('wellness','vaccination_review','parasite_prevention','dental','nutrition_weight','behavior','screening','microchip','senior_care','other')),title text not null check(length(title) between 1 and 120),summary text not null check(length(summary) between 1 and 500),discussion_prompt text not null check(length(discussion_prompt) between 1 and 500),life_stage text check(life_stage in ('young','adult','senior')),priority integer not null default 100 check(priority between 0 and 1000),active boolean not null default true,version integer not null default 1 check(version>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.pet_preventive_guidance_states (
 id uuid primary key default gen_random_uuid(),pet_id uuid not null references public.pets(id),rule_id uuid not null references public.preventive_guidance_rules(id),user_id uuid not null references auth.users(id),rule_version integer not null check(rule_version>0),state text not null check(state in ('active','snoozed','not_relevant','discussed')),snoozed_until date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(pet_id,rule_id,user_id),check((state='snoozed')=(snoozed_until is not null)),check(snoozed_until is null or isfinite(snoozed_until))
);
create table public.pet_preventive_profiles (
 pet_id uuid primary key references public.pets(id),indoor_outdoor text check(indoor_outdoor in ('indoor','mostly_indoor','mixed','mostly_outdoor','outdoor')),social_exposure text check(social_exposure in ('minimal','some','frequent')),travel_frequency text check(travel_frequency in ('rare','occasional','frequent')),boarding_grooming_exposure boolean,wildlife_exposure boolean,owner_notes text check(length(owner_notes)<=500),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now()
);
-- One source, four original high-level paraphrases per supported species; no copied guideline text.
insert into public.preventive_guidance_sources(source_key,publisher,title,source_url,publication_year,reviewed_at) values('aaha_avma_preventive_2011','AAHA / AVMA','2011 AAHA/AVMA Preventive Healthcare Guidelines','https://www.aaha.org/resources/2011-aaha-avma-preventive-healthcare-guidelines/',2011,'2026-09-12T00:00:00Z');
insert into public.preventive_guidance_rules(rule_key,source_id,species,category,title,summary,discussion_prompt,priority)
select sp||'_'||topic.category,s.id,sp,topic.category,topic.title,topic.summary,topic.prompt,topic.priority from public.preventive_guidance_sources s cross join unnest(array['dog','cat']) sp cross join (values
 ('wellness','Routine wellness care','Veterinary checkups offer a place to review preventive care.','Ask your veterinarian how often to arrange a wellness visit.',10),
 ('dental','Dental health','Dental assessment is part of general preventive care.','Ask your veterinarian about dental assessment and suitable home care.',20),
 ('parasite_prevention','Parasite prevention','Parasite prevention can be discussed in the context of your pet’s individual circumstances.','Ask your veterinarian which prevention approach fits your pet.',30),
 ('vaccination_review','Vaccination review','A vaccination plan depends on individual circumstances.','Ask your veterinarian to review the vaccination records and explain any next dates.',40)
)topic(category,title,summary,prompt,priority) where s.source_key='aaha_avma_preventive_2011';

create function public.pc_owner(p_pet uuid) returns void language plpgsql stable security definer set search_path='' as $$begin
 if auth.uid() is null or not exists(select 1 from public.pets p join public.households h on h.id=p.household_id where p.id=p_pet and h.owner_id=auth.uid()) then raise exception 'Preventive care unavailable';end if;end $$;
create function public.pc_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
 if tg_table_name='preventive_guidance_rules' then
 if (new.id,new.rule_key,new.created_at) is distinct from (old.id,old.rule_key,old.created_at) or new.version<old.version then raise exception 'Rule identity immutable';end if;
 if (new.source_id,new.species,new.category,new.title,new.summary,new.discussion_prompt,new.life_stage) is distinct from (old.source_id,old.species,old.category,old.title,old.summary,old.discussion_prompt,old.life_stage) and new.version<=old.version then raise exception 'Content changes require a new version';end if;new.updated_at:=now();return new;
 elsif tg_op='UPDATE' then
 if new.pet_id<>old.pet_id then raise exception 'Pet identity immutable';end if;
 if tg_table_name='pet_preventive_guidance_states' then if (new.id,new.rule_id,new.user_id,new.created_at) is distinct from (old.id,old.rule_id,old.user_id,old.created_at) then raise exception 'State identity immutable';end if;end if;
 end if;
 if tg_table_name='pet_preventive_guidance_states' then if not exists(select 1 from public.pets p join public.households h on h.id=p.household_id where p.id=new.pet_id and h.owner_id=new.user_id) then raise exception 'Invalid owner';end if;end if;
 if tg_table_name='pet_preventive_profiles' then if not exists(select 1 from public.pets p join public.households h on h.id=p.household_id where p.id=new.pet_id and h.owner_id=new.updated_by) then raise exception 'Invalid owner';end if;end if;
 new.updated_at:=now();return new;end $$;
create trigger pc_rule_version before update on public.preventive_guidance_rules for each row execute function public.pc_guard();
create trigger pc_state_identity before insert or update on public.pet_preventive_guidance_states for each row execute function public.pc_guard();
create trigger pc_profile_identity before insert or update on public.pet_preventive_profiles for each row execute function public.pc_guard();
-- No age/lifestyle inference. Unknown species and any stage-specific rule fail closed.
create function public.preventive_rule_applies(p_pet uuid,p_rule uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.pets p join public.preventive_guidance_rules r on r.id=p_rule join public.preventive_guidance_sources s on s.id=r.source_id where p.id=p_pet and lower(btrim(p.species))=r.species and r.life_stage is null and r.active and s.active)$$;
create function public.my_pet_preventive_profile(p_pet uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform public.pc_owner(p_pet);return (select jsonb_build_object('indoor_outdoor',indoor_outdoor,'social_exposure',social_exposure,'travel_frequency',travel_frequency,'boarding_grooming_exposure',boarding_grooming_exposure,'wildlife_exposure',wildlife_exposure,'owner_notes',owner_notes) from public.pet_preventive_profiles where pet_id=p_pet);end $$;
create function public.save_pet_preventive_profile(p_pet uuid,p_data jsonb) returns void language plpgsql security definer set search_path='' as $$begin
 perform public.pc_owner(p_pet);
 if jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>4000 or exists(select 1 from jsonb_object_keys(p_data) k where k not in ('indoor_outdoor','social_exposure','travel_frequency','boarding_grooming_exposure','wildlife_exposure','owner_notes')) or exists(select 1 from jsonb_each(p_data) e where (e.key in ('boarding_grooming_exposure','wildlife_exposure') and jsonb_typeof(e.value) not in ('boolean','null')) or (e.key not in ('boarding_grooming_exposure','wildlife_exposure') and jsonb_typeof(e.value) not in ('string','null'))) then raise exception 'Invalid profile fields';end if;
 insert into public.pet_preventive_profiles(pet_id,indoor_outdoor,social_exposure,travel_frequency,boarding_grooming_exposure,wildlife_exposure,owner_notes,updated_by) values(p_pet,p_data->>'indoor_outdoor',p_data->>'social_exposure',p_data->>'travel_frequency',(p_data->>'boarding_grooming_exposure')::boolean,(p_data->>'wildlife_exposure')::boolean,p_data->>'owner_notes',auth.uid()) on conflict(pet_id) do update set indoor_outdoor=excluded.indoor_outdoor,social_exposure=excluded.social_exposure,travel_frequency=excluded.travel_frequency,boarding_grooming_exposure=excluded.boarding_grooming_exposure,wildlife_exposure=excluded.wildlife_exposure,owner_notes=excluded.owner_notes,updated_by=auth.uid();end $$;
create function public.set_preventive_guidance_state(p_pet uuid,p_rule_key text,p_state text,p_snoozed_until date default null,p_zone text default 'UTC') returns void language plpgsql security definer set search_path='' as $$declare r public.preventive_guidance_rules;today date;begin
 perform public.pc_owner(p_pet);if not exists(select 1 from pg_catalog.pg_timezone_names where name=p_zone) then raise exception 'Invalid time zone';end if;today:=(now() at time zone p_zone)::date;
 select * into r from public.preventive_guidance_rules where rule_key=p_rule_key and public.preventive_rule_applies(p_pet,id) for share;if r.id is null then raise exception 'Topic unavailable';end if;
 if p_state is null or p_state not in ('active','snoozed','not_relevant','discussed') or (p_state='snoozed' and (p_snoozed_until is null or not isfinite(p_snoozed_until) or p_snoozed_until<=today or p_snoozed_until>today+93)) or (p_state<>'snoozed' and p_snoozed_until is not null) then raise exception 'Choose a reminder date within three months';end if;
 insert into public.pet_preventive_guidance_states(pet_id,rule_id,user_id,rule_version,state,snoozed_until) values(p_pet,r.id,auth.uid(),r.version,p_state,p_snoozed_until) on conflict(pet_id,rule_id,user_id) do update set rule_version=excluded.rule_version,state=excluded.state,snoozed_until=excluded.snoozed_until;
end $$;
create function public.pc_guidance(p_pet uuid,p_today date,p_include_hidden boolean default false) returns jsonb language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_agg(item order by priority,title,rule_key),'[]') from (select r.priority,r.title,r.rule_key,jsonb_build_object('id','guidance:'||r.rule_key||':'||r.version,'itemType','guidance','category',r.category,'title',r.title,'date',null,'status',coalesce(st.state,'active'),'sourceType','pawport_guidance','sourceLabel','Pawport preventive-care guidance','trustLevel','guidance','actionUrl','/pets/'||p_pet::text||'/care/guidance/'||r.rule_key,'explanation','Pawport shows this general topic for '||r.species||'s. Your veterinarian can determine what is appropriate based on age, lifestyle, location and medical history.','summary',r.summary,'discussionPrompt',r.discussion_prompt,'ruleKey',r.rule_key,'ruleVersion',r.version,'stateVersion',st.rule_version,'snoozedUntil',st.snoozed_until,'source',jsonb_build_object('sourceKey',s.source_key,'publisher',s.publisher,'title',s.title,'url',s.source_url,'publicationYear',s.publication_year),'contentReviewedAt',s.reviewed_at) item from public.preventive_guidance_rules r join public.preventive_guidance_sources s on s.id=r.source_id left join public.pet_preventive_guidance_states st on st.rule_id=r.id and st.pet_id=p_pet and st.user_id=auth.uid() where public.preventive_rule_applies(p_pet,r.id) and (p_include_hidden or st.state is null or st.state='active' or (st.state='snoozed' and st.snoozed_until<=p_today)) order by r.priority,r.title,r.rule_key limit 50)x
$$;
create function public.preventive_guidance_detail(p_pet uuid,p_rule_key text,p_zone text default 'UTC') returns jsonb language plpgsql stable security definer set search_path='' as $$begin
 perform public.pc_owner(p_pet);if not exists(select 1 from pg_catalog.pg_timezone_names where name=p_zone) then raise exception 'Invalid time zone';end if;
 return (select v from jsonb_array_elements(public.pc_guidance(p_pet,(now() at time zone p_zone)::date,true))v where v->>'ruleKey'=p_rule_key);end $$;
-- Authoritative source tables are normalized here; no duplicate fact persistence.
create function public.my_pet_preventive_care(p_pet uuid,p_zone text default 'UTC') returns jsonb language plpgsql stable security definer set search_path='' as $$declare result jsonb;today date;begin
 perform public.pc_owner(p_pet);if not exists(select 1 from pg_catalog.pg_timezone_names where name=p_zone) then raise exception 'Invalid time zone';end if;today:=(now() at time zone p_zone)::date;
 with vaccines as (
 select v.id,v.name,case when isfinite(v.due_on) then v.due_on end due_on,case t->>'verification_status' when 'provider_verified' then 'vet_verified' when 'document_supported' then 'document_supported' else 'owner_entered' end src from public.vaccinations v cross join lateral jsonb_array_elements(public.owner_vaccination_trust(p_pet)) t where v.pet_id=p_pet and v.id=(t->>'vaccination_id')::uuid
 ), facts as (
 select jsonb_build_object('id','vaccination:'||id::text,'itemType','record','category','vaccination','title',name||' vaccination record','date',due_on,'status',case when due_on is null then 'date_not_recorded' when due_on<today then 'expired' when due_on=today then 'expires_today' else 'upcoming' end,'sourceType',src,'sourceLabel',case src when 'vet_verified' then 'Vet verified' when 'document_supported' then 'From your uploaded record' else 'Owner entered' end,'trustLevel',case src when 'vet_verified' then 'authoritative' when 'document_supported' then 'supported' else 'owner' end,'actionUrl','/pets/'||p_pet::text||'/records','explanation',case when due_on is null then 'No next date is recorded. Ask your veterinarian when this is next due.' else 'This is the expiration date stored on the record, not a calculated vaccination recommendation.' end) item,due_on from vaccines
 ), visits as (
 select jsonb_build_object('id','appointment:'||id::text,'itemType','appointment','category','appointment','title',title,'date',starts_at,'timeZone',time_zone,'status',status,'sourceType','appointment','sourceLabel','Scheduled appointment','trustLevel','owner','actionUrl','/appointments/'||id::text,'explanation',coalesce(provider_name,'Scheduled care')) item,starts_at from public.appointments where pet_id=p_pet and status in ('scheduled','confirmed') and starts_at>=now() and starts_at<now()+interval '90 days' order by starts_at,id limit 25
 ), routines as (
 select jsonb_build_object('id','care:'||cp.id::text,'itemType','routine','category',cp.category,'title',cp.title,'date',coalesce(o.snoozed_until,o.scheduled_for),'timeZone',cp.time_zone,'status',case when o.id is null then 'no_pending_occurrence' when o.snoozed_until is not null then 'snoozed' when o.scheduled_for<now() then 'past_owner_date' else 'upcoming' end,'sourceType','care_plan','sourceLabel','Your care plan','trustLevel','owner','actionUrl','/care/plans/'||cp.id::text,'explanation','An owner-entered routine. Pawport does not medically recommend this schedule.') item,coalesce(o.snoozed_until,o.scheduled_for) due from public.care_plans cp left join public.care_plan_occurrences o on o.plan_id=cp.id and o.status='pending' where cp.pet_id=p_pet and cp.status='active' order by coalesce(o.snoozed_until,o.scheduled_for) nulls last,cp.id limit 50
 ), upcoming as (select item,due_on::timestamp at time zone p_zone at from facts where due_on>today and due_on<=today+90 union all select item,starts_at from visits union all select item,due from routines where due>=now() and due<now()+interval '90 days')
 select jsonb_build_object('pet',(select jsonb_build_object('id',id,'name',name,'species',species) from public.pets where id=p_pet),'needsAttention',coalesce((select jsonb_agg(item order by due_on,item->>'id') from (select * from facts where due_on<=today order by due_on limit 50)x),'[]'),'upcoming',coalesce((select jsonb_agg(item order by at,item->>'id') from (select * from upcoming order by at,item->>'id' limit 50)x),'[]'),'routines',coalesce((select jsonb_agg(item order by due nulls last,item->>'id') from routines),'[]'),'records',coalesce((select jsonb_agg(item order by due_on nulls last,item->>'id') from (select * from facts where due_on is null or due_on>today+90 order by due_on nulls last,item->>'id' limit 50)x),'[]'),'guidance',public.pc_guidance(p_pet,today),'savedGuidance',public.pc_guidance(p_pet,today,true)) into result;return result;
end $$;
create function public.my_preventive_care_summary(p_zone text default 'UTC') returns jsonb language plpgsql stable security definer set search_path='' as $$declare p record;d jsonb;result jsonb:='[]';begin
 for p in select p.id,p.name from public.pets p join public.households h on h.id=p.household_id where h.owner_id=auth.uid() order by p.name,p.id limit 20 loop
 d:=public.my_pet_preventive_care(p.id,p_zone);result:=result||jsonb_build_array(jsonb_build_object('petId',p.id,'petName',p.name,'attentionCount',jsonb_array_length(d->'needsAttention'),'upcomingCount',jsonb_array_length(d->'upcoming'),'guidanceCount',jsonb_array_length(d->'guidance')));end loop;
 if auth.uid() is null then raise exception 'Preventive care unavailable';end if;return result;end $$;
do $$declare t text;f record;begin
 foreach t in array array['preventive_guidance_sources','preventive_guidance_rules','pet_preventive_guidance_states','pet_preventive_profiles'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);end loop;
 for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (left(p.proname,3)='pc_' or p.proname in ('preventive_rule_applies','my_pet_preventive_profile','save_pet_preventive_profile','set_preventive_guidance_state','preventive_guidance_detail','my_pet_preventive_care','my_preventive_care_summary')) loop execute format('revoke all on function %s from public,anon,authenticated',f.sig);end loop;end $$;
grant execute on function public.my_pet_preventive_profile(uuid),public.save_pet_preventive_profile(uuid,jsonb),public.set_preventive_guidance_state(uuid,text,text,date,text),public.preventive_guidance_detail(uuid,text,text),public.my_pet_preventive_care(uuid,text),public.my_preventive_care_summary(text) to authenticated;
commit;
