begin;
create table public.pet_coverage_plans(
 id uuid primary key default gen_random_uuid(),household_id uuid not null references public.households(id),pet_id uuid not null references public.pets(id),created_by uuid not null references auth.users(id),coverage_kind text not null check(coverage_kind in ('accident_only','accident_illness','insurance_other','wellness_program')),carrier_name text not null check(length(btrim(carrier_name)) between 1 and 160),plan_name text check(length(plan_name)<=160),policy_number text check(length(policy_number)<=128 and policy_number !~ '[[:cntrl:]]'),member_number text check(length(member_number)<=128 and member_number !~ '[[:cntrl:]]'),status text not null check(status in ('active','future','expired','cancelled','unknown')),provenance text not null default 'owner_entered' check(provenance in ('owner_entered','document_attached','carrier_verified')) check(provenance<>'carrier_verified'),started_on date,ended_on date,renewal_on date,customer_service_phone text check(length(customer_service_phone)<=40),claims_phone text check(length(claims_phone)<=40),portal_url text check(length(portal_url)<=2048 and portal_url ~ '^https://[^/[:space:]]+' and portal_url !~ '[[:cntrl:]]'),notes text check(length(notes)<=1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(started_on between date '1900-01-01' and date '2199-12-31'),check(ended_on between date '1900-01-01' and date '2199-12-31'),check(renewal_on between date '1900-01-01' and date '2199-12-31'),check(ended_on>=started_on)
);
create index coverage_pet on public.pet_coverage_plans(pet_id,created_at);
create table public.pet_coverage_terms(
 id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.pet_coverage_plans(id),version integer not null check(version>0),effective_on date,ends_on date,deductible_amount_cents bigint check(deductible_amount_cents between 0 and 9000000000000),reimbursement_percent numeric check(reimbursement_percent between 1 and 100),annual_limit_cents bigint check(annual_limit_cents between 0 and 9000000000000),annual_limit_unlimited boolean not null default false,coverage_start_on date,waiting_period_notes text check(length(waiting_period_notes)<=1000),terms_notes text check(length(terms_notes)<=1000),provenance text not null default 'owner_entered' check(provenance='owner_entered'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(plan_id,version),check(not annual_limit_unlimited or annual_limit_cents is null),check(effective_on between date '1900-01-01' and date '2199-12-31'),check(ends_on between date '1900-01-01' and date '2199-12-31'),check(coverage_start_on between date '1900-01-01' and date '2199-12-31'),check(ends_on>=effective_on)
);
create table public.coverage_documents(
 id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.pet_coverage_plans(id),pet_id uuid not null references public.pets(id),uploaded_by uuid not null references auth.users(id),document_type text not null check(document_type in ('policy','insurance_card','renewal_notice','claim_form','explanation_of_benefits','invoice','receipt','correspondence','other')),original_filename text not null check(length(original_filename) between 1 and 255 and original_filename !~ '[[:cntrl:]/\\]'),mime_type text not null check(mime_type in ('application/pdf','image/jpeg','image/png')),size_bytes bigint not null check(size_bytes between 1 and 10485760),object_path text not null unique,status text not null default 'pending' check(status in ('pending','ready','retired')),created_at timestamptz not null default now()
);
create index coverage_document_plan on public.coverage_documents(plan_id,status);
create table public.insurance_claims(
 id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.pet_coverage_plans(id),pet_id uuid not null references public.pets(id),household_id uuid not null references public.households(id),created_by uuid not null references auth.users(id),claim_number text check(length(claim_number)<=128 and claim_number !~ '[[:cntrl:]]'),title text not null check(length(btrim(title)) between 1 and 160),service_date date,provider_name text check(length(provider_name)<=160),status text not null default 'draft' check(status in ('draft','submitted','received','in_review','more_information_needed','approved','partially_approved','denied','paid','closed')),source text not null default 'owner_entered' check(source in ('owner_entered','carrier_verified')) check(source='owner_entered'),submitted_on date,closed_on date,amount_submitted_cents bigint check(amount_submitted_cents between 0 and 9000000000000),amount_approved_cents bigint check(amount_approved_cents between 0 and 9000000000000),amount_reimbursed_cents bigint check(amount_reimbursed_cents between 0 and 9000000000000),owner_out_of_pocket_cents bigint check(owner_out_of_pocket_cents between 0 and 9000000000000),insurer_note text check(length(insurer_note)<=1000),owner_note text check(length(owner_note)<=1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(service_date between date '1900-01-01' and date '2199-12-31'),check(submitted_on between date '1900-01-01' and date '2199-12-31'),check(closed_on between date '1900-01-01' and date '2199-12-31')
);
create index insurance_claim_plan on public.insurance_claims(plan_id,created_at desc);
create table public.insurance_claim_events(id uuid primary key default gen_random_uuid(),claim_id uuid not null references public.insurance_claims(id),actor_id uuid not null references auth.users(id),event_type text not null check(event_type in ('claim_created','status_changed','amount_updated','document_attached','document_removed','claim_closed')),previous_status text,new_status text,note text check(length(note)<=500),created_at timestamptz not null default now());
create index insurance_claim_history on public.insurance_claim_events(claim_id,created_at,id);
create table public.insurance_claim_documents(claim_id uuid not null references public.insurance_claims(id),document_id uuid not null references public.coverage_documents(id),created_at timestamptz not null default now(),primary key(claim_id,document_id));
create function public.ins_owner(p_pet uuid) returns void language plpgsql stable security definer set search_path='' as $$begin if auth.uid() is null or not exists(select 1 from public.pets p join public.households h on h.id=p.household_id where p.id=p_pet and h.owner_id=auth.uid()) then raise exception 'Coverage unavailable';end if;end $$;
create function public.ins_plan(p_pet uuid,p_plan uuid) returns public.pet_coverage_plans language plpgsql stable security definer set search_path='' as $$declare p public.pet_coverage_plans;begin perform public.ins_owner(p_pet);select * into p from public.pet_coverage_plans where id=p_plan and pet_id=p_pet;if p.id is null then raise exception 'Coverage unavailable';end if;return p;end $$;
create function public.ins_object(p_data jsonb,p_keys text[]) returns void language plpgsql immutable set search_path='' as $$begin if jsonb_typeof(p_data) is distinct from 'object' or octet_length(p_data::text)>16000 or exists(select 1 from jsonb_object_keys(p_data) k where not(k=any(p_keys))) then raise exception 'Invalid fields';end if;end $$;
create function public.ins_date(v text) returns date language plpgsql immutable set search_path='' as $$begin if v is null or v='' then return null;end if;if v !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'Invalid date';end if;return v::date;end $$;
create function public.ins_cents(v text) returns bigint language plpgsql immutable set search_path='' as $$begin if v is null or v='' then return null;end if;if v !~ '^\d{1,13}$' or v::bigint>9000000000000 then raise exception 'Invalid amount';end if;return v::bigint;end $$;
create function public.ins_mask(v text) returns text language sql immutable set search_path='' as $$select case when nullif(btrim(v),'') is null then null when length(btrim(v))<4 then '••••' else '•••• '||right(btrim(v),4) end$$;
create function public.ins_immutable() returns trigger language plpgsql set search_path='' as $$begin
 if tg_table_name in ('pet_coverage_terms','insurance_claim_events') then raise exception 'History immutable';end if;
 if tg_op='DELETE' then raise exception 'History cannot be deleted';end if;
 if tg_table_name='pet_coverage_plans' then if (new.id,new.household_id,new.pet_id,new.created_by,new.created_at) is distinct from (old.id,old.household_id,old.pet_id,old.created_by,old.created_at) then raise exception 'Coverage identity immutable';end if;
 elsif tg_table_name='insurance_claims' then if (new.id,new.plan_id,new.household_id,new.pet_id,new.created_by,new.source,new.created_at) is distinct from (old.id,old.plan_id,old.household_id,old.pet_id,old.created_by,old.source,old.created_at) then raise exception 'Claim identity immutable';end if;
 elsif tg_table_name='coverage_documents' then if (new.id,new.plan_id,new.pet_id,new.uploaded_by,new.document_type,new.original_filename,new.mime_type,new.size_bytes,new.object_path,new.created_at) is distinct from (old.id,old.plan_id,old.pet_id,old.uploaded_by,old.document_type,old.original_filename,old.mime_type,old.size_bytes,old.object_path,old.created_at) then raise exception 'Document identity immutable';end if;
 end if;return new;end $$;
do $$declare t text;begin foreach t in array array['pet_coverage_plans','pet_coverage_terms','insurance_claims','insurance_claim_events','coverage_documents'] loop execute format('create trigger insurance_identity before update or delete on public.%I for each row execute function public.ins_immutable()',t);end loop;end $$;
create function public.save_pet_coverage_plan(p_pet uuid,p_plan uuid,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare v_id uuid;begin
 perform public.ins_owner(p_pet);perform 1 from public.pets where pets.id=p_pet for update;
 perform public.ins_object(p_data,array['coverage_kind','carrier_name','plan_name','policy_number','member_number','status','started_on','ended_on','renewal_on','customer_service_phone','claims_phone','portal_url','notes']);
 if p_plan is null then
 if (select count(*) from public.pet_coverage_plans where pet_id=p_pet)>=25 then raise exception 'Coverage plan limit reached';end if;
 insert into public.pet_coverage_plans(household_id,pet_id,created_by,coverage_kind,carrier_name,status) select household_id,p_pet,auth.uid(),p_data->>'coverage_kind',p_data->>'carrier_name',p_data->>'status' from public.pets where pets.id=p_pet returning pet_coverage_plans.id into v_id;
 else perform public.ins_plan(p_pet,p_plan);v_id:=p_plan;end if;
 update public.pet_coverage_plans set coverage_kind=p_data->>'coverage_kind',carrier_name=p_data->>'carrier_name',plan_name=nullif(p_data->>'plan_name',''),policy_number=nullif(p_data->>'policy_number',''),member_number=nullif(p_data->>'member_number',''),status=p_data->>'status',started_on=public.ins_date(p_data->>'started_on'),ended_on=public.ins_date(p_data->>'ended_on'),renewal_on=public.ins_date(p_data->>'renewal_on'),customer_service_phone=nullif(p_data->>'customer_service_phone',''),claims_phone=nullif(p_data->>'claims_phone',''),portal_url=nullif(p_data->>'portal_url',''),notes=nullif(p_data->>'notes',''),updated_at=now() where pet_coverage_plans.id=v_id;return v_id;end $$;
create function public.add_pet_coverage_term(p_pet uuid,p_plan uuid,p_data jsonb) returns integer language plpgsql security definer set search_path='' as $$declare v integer;begin
 perform public.ins_plan(p_pet,p_plan);perform 1 from public.pet_coverage_plans where id=p_plan for update;
 perform public.ins_object(p_data,array['effective_on','ends_on','deductible_amount_cents','reimbursement_percent','annual_limit_cents','annual_limit_unlimited','coverage_start_on','waiting_period_notes','terms_notes']);
 select coalesce(max(version),0)+1 into v from public.pet_coverage_terms where plan_id=p_plan;if v>100 then raise exception 'Term limit reached';end if;
 if p_data ? 'annual_limit_unlimited' and jsonb_typeof(p_data->'annual_limit_unlimited')<>'boolean' then raise exception 'Invalid annual limit';end if;
 insert into public.pet_coverage_terms(plan_id,version,effective_on,ends_on,deductible_amount_cents,reimbursement_percent,annual_limit_cents,annual_limit_unlimited,coverage_start_on,waiting_period_notes,terms_notes) values(p_plan,v,public.ins_date(p_data->>'effective_on'),public.ins_date(p_data->>'ends_on'),public.ins_cents(p_data->>'deductible_amount_cents'),nullif(p_data->>'reimbursement_percent','')::numeric,public.ins_cents(p_data->>'annual_limit_cents'),coalesce((p_data->>'annual_limit_unlimited')::boolean,false),public.ins_date(p_data->>'coverage_start_on'),p_data->>'waiting_period_notes',p_data->>'terms_notes');return v;end $$;
create function public.save_insurance_claim(p_pet uuid,p_plan uuid,p_claim uuid,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare p public.pet_coverage_plans;old public.insurance_claims;n public.insurance_claims;v_id uuid;begin
 p:=public.ins_plan(p_pet,p_plan);perform 1 from public.pet_coverage_plans where pet_coverage_plans.id=p_plan for update;
 perform public.ins_object(p_data,array['claim_number','title','service_date','provider_name','status','submitted_on','closed_on','amount_submitted_cents','amount_approved_cents','amount_reimbursed_cents','owner_out_of_pocket_cents','insurer_note','owner_note']);
 if p_claim is null then
 if (select count(*) from public.insurance_claims where plan_id=p_plan)>=200 then raise exception 'Claim limit reached';end if;
 insert into public.insurance_claims(plan_id,pet_id,household_id,created_by,title) values(p_plan,p_pet,p.household_id,auth.uid(),p_data->>'title') returning insurance_claims.id into v_id;
 else select * into old from public.insurance_claims where insurance_claims.id=p_claim and plan_id=p_plan for update;if old.id is null then raise exception 'Claim unavailable';end if;v_id:=old.id;end if;
 update public.insurance_claims set claim_number=nullif(p_data->>'claim_number',''),title=p_data->>'title',service_date=public.ins_date(p_data->>'service_date'),provider_name=nullif(p_data->>'provider_name',''),status=coalesce(p_data->>'status','draft'),submitted_on=public.ins_date(p_data->>'submitted_on'),closed_on=public.ins_date(p_data->>'closed_on'),amount_submitted_cents=public.ins_cents(p_data->>'amount_submitted_cents'),amount_approved_cents=public.ins_cents(p_data->>'amount_approved_cents'),amount_reimbursed_cents=public.ins_cents(p_data->>'amount_reimbursed_cents'),owner_out_of_pocket_cents=public.ins_cents(p_data->>'owner_out_of_pocket_cents'),insurer_note=p_data->>'insurer_note',owner_note=p_data->>'owner_note',updated_at=now() where insurance_claims.id=v_id returning * into n;
 if old.id is null then insert into public.insurance_claim_events(claim_id,actor_id,event_type,new_status) values(v_id,auth.uid(),'claim_created',n.status);
 else
 if n.status<>old.status then insert into public.insurance_claim_events(claim_id,actor_id,event_type,previous_status,new_status) values(v_id,auth.uid(),'status_changed',old.status,n.status);if n.status='closed' then insert into public.insurance_claim_events(claim_id,actor_id,event_type,previous_status,new_status) values(v_id,auth.uid(),'claim_closed',old.status,n.status);end if;end if;
 if (n.amount_submitted_cents,n.amount_approved_cents,n.amount_reimbursed_cents,n.owner_out_of_pocket_cents) is distinct from (old.amount_submitted_cents,old.amount_approved_cents,old.amount_reimbursed_cents,old.owner_out_of_pocket_cents) then insert into public.insurance_claim_events(claim_id,actor_id,event_type) values(v_id,auth.uid(),'amount_updated');end if;end if;return v_id;end $$;
-- Only supporting document presence changes plan-level evidence; individual terms stay owner-entered.
create function public.ins_document_provenance() returns trigger language plpgsql security definer set search_path='' as $$begin
 update public.pet_coverage_plans set provenance=case when exists(select 1 from public.coverage_documents where plan_id=new.plan_id and status='ready' and document_type in ('policy','insurance_card','renewal_notice')) then 'document_attached' else 'owner_entered' end where id=new.plan_id;return new;end $$;
create trigger coverage_document_evidence after insert or update of status on public.coverage_documents for each row execute function public.ins_document_provenance();
create function public.prepare_coverage_document(p_pet uuid,p_plan uuid,p_name text,p_type text,p_mime text,p_size bigint) returns jsonb language plpgsql security definer set search_path='' as $$declare p public.pet_coverage_plans;d uuid:=gen_random_uuid();path text;begin
 p:=public.ins_plan(p_pet,p_plan);perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('insurance-upload:'||auth.uid()::text,0));perform 1 from public.pet_coverage_plans where id=p_plan for update;
 if p_size is null or p_size not between 1 and 10485760 or p_mime is null or not((p_mime='application/pdf' and p_name ~* '\.pdf$') or (p_mime='image/jpeg' and p_name ~* '\.(jpeg|jpg)$') or (p_mime='image/png' and p_name ~* '\.png$')) then raise exception 'Invalid document';end if;
 update public.coverage_documents set status='retired' where plan_id=p_plan and status='pending' and created_at<now()-interval '1 hour';
 if (select count(*) from public.coverage_documents where plan_id=p_plan and status<>'retired')>=100 or (select count(*) from public.coverage_documents where uploaded_by=auth.uid() and created_at>now()-interval '1 day')>=50 then raise exception 'Document limit reached';end if;
 path:='insurance/'||p.household_id||'/'||p.pet_id||'/'||d;
 insert into public.coverage_documents(id,plan_id,pet_id,uploaded_by,document_type,original_filename,mime_type,size_bytes,object_path) values(d,p_plan,p_pet,auth.uid(),p_type,p_name,p_mime,p_size,path);return jsonb_build_object('id',d,'path',path);end $$;
create function public.finalize_coverage_document(p_document uuid) returns void language plpgsql security definer set search_path='' as $$declare d public.coverage_documents;begin
 select * into d from public.coverage_documents where id=p_document;if d.id is null then raise exception 'Document unavailable';end if;perform public.ins_plan(d.pet_id,d.plan_id);perform 1 from public.pet_coverage_plans where id=d.plan_id for update;select * into d from public.coverage_documents where id=p_document for update;
 if d.status='ready' then return;end if;if d.status<>'pending' or d.created_at<now()-interval '1 hour' then raise exception 'Upload expired';end if;
 if not exists(select 1 from storage.objects where bucket_id='insurance-documents' and name=d.object_path and metadata->>'mimetype'=d.mime_type and (metadata->>'size')::bigint=d.size_bytes) then raise exception 'Document missing or invalid';end if;update public.coverage_documents set status='ready' where id=d.id;end $$;
create function public.set_insurance_claim_document(p_pet uuid,p_plan uuid,p_claim uuid,p_document uuid,p_attached boolean) returns void language plpgsql security definer set search_path='' as $$begin
 perform public.ins_plan(p_pet,p_plan);perform 1 from public.pet_coverage_plans where id=p_plan for update;
 if not exists(select 1 from public.insurance_claims where id=p_claim and plan_id=p_plan and pet_id=p_pet) or not exists(select 1 from public.coverage_documents where id=p_document and plan_id=p_plan and pet_id=p_pet and status='ready') then raise exception 'Document or claim unavailable';end if;
 if p_attached then insert into public.insurance_claim_documents(claim_id,document_id) values(p_claim,p_document) on conflict do nothing;else delete from public.insurance_claim_documents where claim_id=p_claim and document_id=p_document;end if;
 if found then insert into public.insurance_claim_events(claim_id,actor_id,event_type) values(p_claim,auth.uid(),case when p_attached then 'document_attached' else 'document_removed' end);end if;end $$;
create function public.retire_coverage_document(p_document uuid) returns void language plpgsql security definer set search_path='' as $$declare d public.coverage_documents;begin
 select * into d from public.coverage_documents where id=p_document;if d.id is null then raise exception 'Document unavailable';end if;perform public.ins_plan(d.pet_id,d.plan_id);perform 1 from public.pet_coverage_plans where id=d.plan_id for update;select * into d from public.coverage_documents where id=p_document for update;if d.status='retired' then return;end if;
 insert into public.insurance_claim_events(claim_id,actor_id,event_type) select claim_id,auth.uid(),'document_removed' from public.insurance_claim_documents where document_id=d.id;delete from public.insurance_claim_documents where document_id=d.id;update public.coverage_documents set status='retired' where id=d.id;end $$;
create function public.my_coverage_document_delivery(p_document uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare d public.coverage_documents;begin select * into d from public.coverage_documents where id=p_document and status='ready';if d.id is null then raise exception 'Document unavailable';end if;perform public.ins_plan(d.pet_id,d.plan_id);return jsonb_build_object('path',d.object_path,'name',d.original_filename,'mime',d.mime_type,'size',d.size_bytes);end $$;
create function public.can_access_coverage_document(p_path text,p_action text) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.coverage_documents d join public.pet_coverage_plans p on p.id=d.plan_id join public.households h on h.id=p.household_id where d.object_path=p_path and h.owner_id=auth.uid() and d.pet_id=p.pet_id and ((p_action='read' and d.status='ready') or (p_action='insert' and d.status='pending' and d.created_at>now()-interval '1 hour')))$$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('insurance-documents','insurance-documents',false,10485760,array['application/pdf','image/jpeg','image/png']);
create policy insurance_document_read on storage.objects for select to authenticated using(bucket_id='insurance-documents' and public.can_access_coverage_document(name,'read'));
create policy insurance_document_insert on storage.objects for insert to authenticated with check(bucket_id='insurance-documents' and public.can_access_coverage_document(name,'insert'));
create policy insurance_document_read_guard on storage.objects as restrictive for select to public using(bucket_id<>'insurance-documents' or public.can_access_coverage_document(name,'read'));
create policy insurance_document_insert_guard on storage.objects as restrictive for insert to public with check(bucket_id<>'insurance-documents' or public.can_access_coverage_document(name,'insert'));
create policy insurance_document_update_guard on storage.objects as restrictive for update to public using(bucket_id<>'insurance-documents') with check(bucket_id<>'insurance-documents');
create policy insurance_document_delete_guard on storage.objects as restrictive for delete to public using(bucket_id<>'insurance-documents');
create function public.ins_integrity() returns trigger language plpgsql security definer set search_path='' as $$declare p public.pet_coverage_plans;begin
 if tg_table_name='pet_coverage_plans' then
 if not exists(select 1 from public.pets pet join public.households h on h.id=pet.household_id where pet.id=new.pet_id and h.id=new.household_id and h.owner_id=new.created_by) then raise exception 'Invalid coverage ownership';end if;
 elsif tg_table_name='insurance_claim_documents' then
 if tg_op='UPDATE' then raise exception 'Link identity immutable';end if;
 if not exists(select 1 from public.insurance_claims c join public.coverage_documents d on d.plan_id=c.plan_id and d.pet_id=c.pet_id where c.id=new.claim_id and d.id=new.document_id and d.status='ready') then raise exception 'Invalid document link';end if;
 else
 select * into p from public.pet_coverage_plans where id=new.plan_id;
 if tg_table_name='insurance_claims' then if (new.pet_id,new.household_id,new.created_by) is distinct from (p.pet_id,p.household_id,p.created_by) then raise exception 'Invalid claim ownership';end if;
 elsif tg_table_name='coverage_documents' then if new.pet_id<>p.pet_id or new.uploaded_by<>p.created_by or new.object_path is distinct from 'insurance/'||p.household_id||'/'||p.pet_id||'/'||new.id then raise exception 'Invalid document ownership';end if;end if;
 end if;return new;end $$;
do $$declare t text;begin foreach t in array array['pet_coverage_plans','insurance_claims','coverage_documents','insurance_claim_documents'] loop execute format('create trigger insurance_integrity before insert or update on public.%I for each row execute function public.ins_integrity()',t);end loop;end $$;
create function public.ins_plan_summary(p public.pet_coverage_plans) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('planId',p.id,'petId',p.pet_id,'carrierName',p.carrier_name,'planName',p.plan_name,'coverageKind',p.coverage_kind,'coverageLabel',case p.coverage_kind when 'wellness_program' then 'Wellness plan — not insurance' when 'accident_only' then 'Accident-only insurance' when 'accident_illness' then 'Accident & illness insurance' else 'Insurance policy' end,'status',p.status,'maskedPolicyNumber',public.ins_mask(case when p.coverage_kind='wellness_program' then p.member_number else p.policy_number end),'renewalOn',p.renewal_on,'provenance',p.provenance,'provenanceLabel',case when p.provenance='document_attached' then case when p.coverage_kind='wellness_program' then 'Plan document attached' else 'Policy document attached' end else 'Owner entered' end,'openClaimCount',(select count(*) from public.insurance_claims c where c.plan_id=p.id and c.status in ('draft','submitted','received','in_review','more_information_needed')))$$;
create function public.my_pet_coverage_plans(p_pet uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform public.ins_owner(p_pet);return(select coalesce(jsonb_agg(public.ins_plan_summary(p) order by p.created_at desc,p.id),'[]') from public.pet_coverage_plans p where p.pet_id=p_pet);end $$;
create function public.my_pet_coverage_claims(p_pet uuid,p_plan uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform public.ins_plan(p_pet,p_plan);return(select coalesce(jsonb_agg(jsonb_build_object('claimId',id,'title',title,'status',status,'source','owner_entered','serviceDate',service_date,'submittedOn',submitted_on,'maskedClaimNumber',public.ins_mask(claim_number),'amountSubmitted',amount_submitted_cents,'amountReimbursed',amount_reimbursed_cents) order by created_at desc,id),'[]') from public.insurance_claims where plan_id=p_plan);end $$;
create function public.my_pet_coverage_plan(p_pet uuid,p_plan uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.pet_coverage_plans;begin
 p:=public.ins_plan(p_pet,p_plan);return jsonb_build_object('summary',public.ins_plan_summary(p),'plan',to_jsonb(p)-array['household_id','created_by'],'terms',coalesce((select jsonb_agg(to_jsonb(t)-'plan_id' order by version desc) from public.pet_coverage_terms t where plan_id=p_plan),'[]'),'documents',coalesce((select jsonb_agg(jsonb_build_object('id',id,'name',original_filename,'type',document_type,'status',status,'mime',mime_type,'size',size_bytes) order by created_at desc,id) from public.coverage_documents where plan_id=p_plan and status<>'retired'),'[]'),'claims',public.my_pet_coverage_claims(p_pet,p_plan));end $$;
create function public.my_insurance_claim(p_pet uuid,p_plan uuid,p_claim uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare c public.insurance_claims;begin perform public.ins_plan(p_pet,p_plan);select * into c from public.insurance_claims where id=p_claim and plan_id=p_plan;if c.id is null then raise exception 'Claim unavailable';end if;
 return jsonb_build_object('claim',to_jsonb(c)-array['household_id','created_by'],'documents',coalesce((select jsonb_agg(document_id) from public.insurance_claim_documents where claim_id=c.id),'[]'),'events',coalesce((select jsonb_agg(jsonb_build_object('id',id,'type',event_type,'previousStatus',previous_status,'newStatus',new_status,'date',created_at) order by created_at desc,id desc) from(select * from public.insurance_claim_events where claim_id=c.id order by created_at desc,id desc limit 100)e),'[]'));end $$;
create function public.my_insurance_summary() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if auth.uid() is null then raise exception 'Coverage unavailable';end if;return (select coalesce(jsonb_agg(jsonb_build_object('petId',p.id,'petName',p.name,'activePlanCount',(select count(*) from public.pet_coverage_plans where pet_id=p.id and status='active' and coverage_kind<>'wellness_program'),'wellnessPlanCount',(select count(*) from public.pet_coverage_plans where pet_id=p.id and coverage_kind='wellness_program'),'openClaimCount',(select count(*) from public.insurance_claims where pet_id=p.id and status in ('draft','submitted','received','in_review','more_information_needed')),'nextRenewalOn',(select min(renewal_on) from public.pet_coverage_plans where pet_id=p.id and renewal_on>=current_date),'plans',public.my_pet_coverage_plans(p.id)) order by p.name,p.id),'[]') from public.pets p join public.households h on h.id=p.household_id where h.owner_id=auth.uid());end $$;
create function public.my_insurance_renewals(p_zone text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare today date;begin if auth.uid() is null or not exists(select 1 from pg_catalog.pg_timezone_names where name=p_zone) then raise exception 'Coverage unavailable';end if;today:=(now() at time zone p_zone)::date;return(select coalesce(jsonb_agg(jsonb_build_object('id','coverage-renewal:'||id,'petName',pet_name,'date',renewal_on,'title',case when coverage_kind='wellness_program' then 'Wellness plan renewal date recorded' else 'Insurance renewal date recorded' end,'sourceLabel','Owner-entered coverage record','actionUrl','/pets/'||pet_id||'/insurance/'||id) order by renewal_on,id),'[]') from(select c.id,c.pet_id,p.name pet_name,c.coverage_kind,c.renewal_on from public.pet_coverage_plans c join public.pets p on p.id=c.pet_id join public.households h on h.id=c.household_id where h.owner_id=auth.uid() and c.renewal_on between today and today+30 order by c.renewal_on,c.id limit 3)x);end $$;
do $$declare t text;f record;begin foreach t in array array['pet_coverage_plans','pet_coverage_terms','coverage_documents','insurance_claims','insurance_claim_events','insurance_claim_documents'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);end loop;
for f in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (left(p.proname,4)='ins_' or p.proname in ('save_pet_coverage_plan','add_pet_coverage_term','save_insurance_claim','prepare_coverage_document','finalize_coverage_document','retire_coverage_document','set_insurance_claim_document','my_coverage_document_delivery','can_access_coverage_document','my_pet_coverage_plans','my_pet_coverage_plan','my_pet_coverage_claims','my_insurance_claim','my_insurance_summary','my_insurance_renewals')) loop execute format('revoke all on function %s from public,anon,authenticated',f.sig);end loop;end $$;
grant execute on function public.save_pet_coverage_plan(uuid,uuid,jsonb),public.add_pet_coverage_term(uuid,uuid,jsonb),public.save_insurance_claim(uuid,uuid,uuid,jsonb),public.prepare_coverage_document(uuid,uuid,text,text,text,bigint),public.finalize_coverage_document(uuid),public.retire_coverage_document(uuid),public.set_insurance_claim_document(uuid,uuid,uuid,uuid,boolean),public.my_coverage_document_delivery(uuid),public.can_access_coverage_document(text,text),public.my_pet_coverage_plans(uuid),public.my_pet_coverage_plan(uuid,uuid),public.my_pet_coverage_claims(uuid,uuid),public.my_insurance_claim(uuid,uuid,uuid),public.my_insurance_summary(),public.my_insurance_renewals(text) to authenticated;
-- Storage guards are evaluated for every bucket, including public logo reads.
-- Anonymous callers receive only false; no document metadata is exposed.
grant execute on function public.can_access_coverage_document(text,text) to anon;
commit;
