begin;
-- Owner-entered financial organization only; no clinical or coverage inference.
create table public.pet_expenses(id uuid primary key default gen_random_uuid(),household_id uuid not null references public.households(id),pet_id uuid not null references public.pets(id),created_by uuid not null references auth.users(id),title text not null check(length(btrim(title)) between 1 and 160),category text not null check(category in ('veterinary','emergency','dental','medication','pharmacy','grooming','boarding','daycare','walking','sitting','training','food','supplies','insurance_premium','wellness_plan','other')),service_date date not null check(service_date between date '2000-01-01' and date '2200-12-31'),provider_name text check(length(provider_name)<=160),amount_cents bigint not null check(amount_cents between 0 and 9000000000000),currency text not null default 'USD' check(currency='USD'),source text not null default 'owner_entered' check(source in ('owner_entered','provider_verified','carrier_verified')) check(source='owner_entered'),appointment_id uuid references public.appointments(id),coverage_plan_id uuid references public.pet_coverage_plans(id),notes text check(length(notes)<=1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index pet_expense_pages on public.pet_expenses(pet_id,service_date desc,created_at desc,id desc);
create table public.expense_claim_allocations(expense_id uuid not null references public.pet_expenses(id),claim_id uuid not null references public.insurance_claims(id),allocated_reimbursement_cents bigint not null check(allocated_reimbursement_cents between 0 and 9000000000000),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(expense_id,claim_id));
create index expense_allocations_claim on public.expense_claim_allocations(claim_id);
create table public.pet_expense_events(id uuid primary key default gen_random_uuid(),expense_id uuid not null references public.pet_expenses(id),actor_id uuid not null references auth.users(id),event_type text not null check(event_type in ('expense_created','expense_updated','claim_linked','claim_unlinked','document_attached','document_removed')),created_at timestamptz not null default now());
create index pet_expense_history on public.pet_expense_events(expense_id,created_at,id);
create table public.pet_planned_costs(id uuid primary key default gen_random_uuid(),household_id uuid not null references public.households(id),pet_id uuid not null references public.pets(id),created_by uuid not null references auth.users(id),title text not null check(length(btrim(title)) between 1 and 160),category text not null check(category in ('veterinary','emergency','dental','medication','pharmacy','grooming','boarding','daycare','walking','sitting','training','food','supplies','insurance_premium','wellness_plan','other')),planned_amount_cents bigint check(planned_amount_cents between 0 and 9000000000000),planning_year integer not null check(planning_year between 2000 and 2200),due_on date check(due_on between date '2000-01-01' and date '2200-12-31'),source text not null default 'owner_entered' check(source in ('owner_entered','provider_quote')) check(source='owner_entered'),appointment_id uuid references public.appointments(id),care_plan_id uuid references public.care_plans(id),status text not null default 'planned' check(status in ('planned','completed','cancelled','converted_to_expense')),converted_expense_id uuid unique references public.pet_expenses(id),notes text check(length(notes)<=1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(due_on is null or extract(year from due_on)=planning_year),check((status='converted_to_expense')=(converted_expense_id is not null)));
create index pet_planning_year on public.pet_planned_costs(pet_id,planning_year,due_on,id);
create table public.pet_cost_budgets(id uuid primary key default gen_random_uuid(),household_id uuid not null references public.households(id),pet_id uuid not null references public.pets(id),created_by uuid not null references auth.users(id),year integer not null check(year between 2000 and 2200),category text not null check(category in ('all_care','veterinary','emergency','dental','medication','pharmacy','grooming','boarding','daycare','walking','sitting','training','food','supplies','insurance_premium','wellness_plan','other')),planned_amount_cents bigint not null check(planned_amount_cents between 0 and 9000000000000),notes text check(length(notes)<=1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(pet_id,year,category));
create table public.expense_documents(id uuid primary key default gen_random_uuid(),expense_id uuid not null references public.pet_expenses(id),pet_id uuid not null references public.pets(id),uploaded_by uuid not null references auth.users(id),document_type text not null check(document_type in ('receipt','invoice','estimate','statement','other')),original_filename text not null check(length(original_filename) between 1 and 255 and original_filename !~ '[[:cntrl:]/\\]'),mime_type text not null check(mime_type in ('application/pdf','image/jpeg','image/png')),size_bytes bigint not null check(size_bytes between 1 and 10485760),object_path text unique not null,status text not null default 'pending' check(status in ('pending','ready','retired')),created_at timestamptz not null default now());
create index expense_document_parent on public.expense_documents(expense_id,status);
create function public.cost_owner(p_pet uuid,p_lock boolean default false) returns uuid language plpgsql security definer set search_path='' as $$declare h uuid;begin select p.household_id into h from public.pets p join public.households hh on hh.id=p.household_id where p.id=p_pet and hh.owner_id=auth.uid();if h is null then raise exception 'Cost information unavailable';end if;if p_lock then perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('cost-pet:'||p_pet,0));end if;return h;end $$;
create function public.cost_year(y integer) returns void language plpgsql immutable set search_path='' as $$begin if y is null or y not between 2000 and 2200 then raise exception 'Invalid planning year';end if;end $$;
create function public.cost_identity() returns trigger language plpgsql security definer set search_path='' as $$begin
 if tg_op='DELETE' or tg_table_name='pet_expense_events' then raise exception 'Financial history is immutable';end if;
 if tg_table_name='expense_documents' then if (new.id,new.expense_id,new.pet_id,new.uploaded_by,new.document_type,new.original_filename,new.mime_type,new.size_bytes,new.object_path,new.created_at) is distinct from (old.id,old.expense_id,old.pet_id,old.uploaded_by,old.document_type,old.original_filename,old.mime_type,old.size_bytes,old.object_path,old.created_at) then raise exception 'Document identity immutable';end if;
 elsif tg_table_name='expense_claim_allocations' then if (new.expense_id,new.claim_id,new.created_by,new.created_at) is distinct from (old.expense_id,old.claim_id,old.created_by,old.created_at) then raise exception 'Allocation identity immutable';end if;
 else if (new.id,new.pet_id,new.household_id,new.created_by,new.created_at) is distinct from (old.id,old.pet_id,old.household_id,old.created_by,old.created_at) then raise exception 'Financial identity immutable';end if;
 if tg_table_name='pet_planned_costs' then if old.converted_expense_id is not null and new is distinct from old then raise exception 'Converted plan is immutable';end if;end if;
 end if;return new;end $$;
do $$declare t text;begin foreach t in array array['pet_expenses','pet_planned_costs','pet_cost_budgets','pet_expense_events','expense_documents'] loop execute format('create trigger cost_identity before update or delete on public.%I for each row execute function public.cost_identity()',t);end loop;end $$;
create trigger allocation_identity before update on public.expense_claim_allocations for each row execute function public.cost_identity();
create function public.cost_integrity() returns trigger language plpgsql security definer set search_path='' as $$declare e public.pet_expenses;c public.insurance_claims;begin
 if tg_table_name='expense_claim_allocations' then
 select * into e from public.pet_expenses where id=new.expense_id for update;select * into c from public.insurance_claims where id=new.claim_id for update;
 if e.id is null or c.id is null or e.coverage_plan_id is distinct from c.plan_id or (e.pet_id,e.household_id,e.created_by) is distinct from (c.pet_id,c.household_id,c.created_by) or new.created_by<>e.created_by then raise exception 'Claim must match this expense pet and coverage plan';end if;
 if c.amount_reimbursed_cents is null then raise exception 'Record the reimbursement on the insurance claim first';end if;
 if new.allocated_reimbursement_cents+coalesce((select sum(allocated_reimbursement_cents) from public.expense_claim_allocations where expense_id=e.id and claim_id<>c.id),0)>e.amount_cents or new.allocated_reimbursement_cents+coalesce((select sum(allocated_reimbursement_cents) from public.expense_claim_allocations where claim_id=c.id and expense_id<>e.id),0)>c.amount_reimbursed_cents then raise exception 'Allocation exceeds recorded expense or reimbursement';end if;
 elsif tg_table_name='expense_documents' then
 select * into e from public.pet_expenses where id=new.expense_id;if new.pet_id is distinct from e.pet_id or new.uploaded_by is distinct from e.created_by or new.object_path is distinct from 'expenses/'||e.household_id||'/'||e.pet_id||'/'||new.id then raise exception 'Invalid expense document';end if;
 else
 if not exists(select 1 from public.pets p join public.households h on h.id=p.household_id where p.id=new.pet_id and h.id=new.household_id and h.owner_id=new.created_by) then raise exception 'Invalid financial ownership';end if;
 if tg_table_name<>'pet_cost_budgets' then
 if new.appointment_id is not null and not exists(select 1 from public.appointments where id=new.appointment_id and pet_id=new.pet_id and household_id=new.household_id) then raise exception 'Appointment must belong to this pet';end if;
 if tg_table_name='pet_expenses' then
 if new.coverage_plan_id is not null and not exists(select 1 from public.pet_coverage_plans where id=new.coverage_plan_id and pet_id=new.pet_id and household_id=new.household_id) then raise exception 'Coverage plan must belong to this pet';end if;
 if coalesce((select sum(allocated_reimbursement_cents) from public.expense_claim_allocations where expense_id=new.id),0)>new.amount_cents or exists(select 1 from public.expense_claim_allocations a join public.insurance_claims linked_claim on linked_claim.id=a.claim_id where a.expense_id=new.id and linked_claim.plan_id is distinct from new.coverage_plan_id) then raise exception 'Adjust reimbursement allocations first';end if;
 else
 if new.care_plan_id is not null and not exists(select 1 from public.care_plans where id=new.care_plan_id and pet_id=new.pet_id and household_id=new.household_id) then raise exception 'Care plan must belong to this pet';end if;
 if new.converted_expense_id is not null and not exists(select 1 from public.pet_expenses where id=new.converted_expense_id and pet_id=new.pet_id and created_by=new.created_by) then raise exception 'Invalid converted expense';end if;
 end if;end if;end if;return new;end $$;
do $$declare t text;begin foreach t in array array['pet_expenses','pet_planned_costs','pet_cost_budgets','expense_claim_allocations','expense_documents'] loop execute format('create trigger cost_integrity before insert or update on public.%I for each row execute function public.cost_integrity()',t);end loop;end $$;
-- Insurance remains authoritative. Reducing its recorded reimbursement must not
-- invalidate explicit allocations; no 9B amount is automatically changed.
create function public.cost_claim_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('cost-pet:'||new.pet_id,0));
 if exists(select 1 from public.expense_claim_allocations where claim_id=new.id) and (new.amount_reimbursed_cents is null or new.amount_reimbursed_cents<(select sum(allocated_reimbursement_cents) from public.expense_claim_allocations where claim_id=new.id)) then raise exception 'Adjust cost allocations before reducing recorded reimbursement';end if;return new;end $$;
create trigger cost_claim_guard before update of amount_reimbursed_cents on public.insurance_claims for each row execute function public.cost_claim_guard();
create function public.save_pet_expense(p_pet uuid,p_expense uuid,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare h uuid;v_id uuid;y integer;begin
 h:=public.cost_owner(p_pet,true);perform public.ins_object(p_data,array['title','category','service_date','provider_name','amount_cents','appointment_id','coverage_plan_id','notes']);y:=extract(year from public.ins_date(p_data->>'service_date'));perform public.cost_year(y);
 if (select count(*) from public.pet_expenses where pet_id=p_pet and extract(year from service_date)=y and id is distinct from p_expense)>=1000 then raise exception 'Yearly expense limit reached';end if;
 if p_expense is null then insert into public.pet_expenses(household_id,pet_id,created_by,title,category,service_date,amount_cents) values(h,p_pet,auth.uid(),p_data->>'title',p_data->>'category',public.ins_date(p_data->>'service_date'),public.ins_cents(p_data->>'amount_cents')) returning id into v_id;
 else select id into v_id from public.pet_expenses where id=p_expense and pet_id=p_pet for update;if v_id is null then raise exception 'Expense unavailable';end if;end if;
 update public.pet_expenses set title=p_data->>'title',category=p_data->>'category',service_date=public.ins_date(p_data->>'service_date'),provider_name=nullif(p_data->>'provider_name',''),amount_cents=public.ins_cents(p_data->>'amount_cents'),appointment_id=nullif(p_data->>'appointment_id','')::uuid,coverage_plan_id=nullif(p_data->>'coverage_plan_id','')::uuid,notes=p_data->>'notes',updated_at=now() where id=v_id;
 insert into public.pet_expense_events(expense_id,actor_id,event_type) values(v_id,auth.uid(),case when p_expense is null then 'expense_created' else 'expense_updated' end);return v_id;end $$;
create function public.set_expense_claim_allocation(p_pet uuid,p_expense uuid,p_claim uuid,p_amount bigint) returns void language plpgsql security definer set search_path='' as $$begin
 perform public.cost_owner(p_pet,true);perform 1 from public.pet_expenses where id=p_expense and pet_id=p_pet for update;if not found then raise exception 'Expense unavailable';end if;
 perform 1 from public.insurance_claims where id=p_claim and pet_id=p_pet and created_by=auth.uid() for update;if not found then raise exception 'Claim unavailable';end if;
 if p_amount is null then delete from public.expense_claim_allocations where expense_id=p_expense and claim_id=p_claim;
 else insert into public.expense_claim_allocations(expense_id,claim_id,allocated_reimbursement_cents,created_by) values(p_expense,p_claim,p_amount,auth.uid()) on conflict(expense_id,claim_id) do update set allocated_reimbursement_cents=excluded.allocated_reimbursement_cents,updated_at=now();end if;
 if found then insert into public.pet_expense_events(expense_id,actor_id,event_type) values(p_expense,auth.uid(),case when p_amount is null then 'claim_unlinked' else 'claim_linked' end);end if;end $$;
create function public.save_pet_planned_cost(p_pet uuid,p_planned uuid,p_data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare h uuid;v_id uuid;y integer;begin
 h:=public.cost_owner(p_pet,true);perform public.ins_object(p_data,array['title','category','planning_year','planned_amount_cents','due_on','appointment_id','care_plan_id','status','notes']);y:=(p_data->>'planning_year')::integer;perform public.cost_year(y);
 if (select count(*) from public.pet_planned_costs where pet_id=p_pet and planning_year=y and id is distinct from p_planned)>=200 then raise exception 'Planning limit reached';end if;
 if p_planned is null then insert into public.pet_planned_costs(household_id,pet_id,created_by,title,category,planning_year) values(h,p_pet,auth.uid(),p_data->>'title',p_data->>'category',y) returning id into v_id;
 else select id into v_id from public.pet_planned_costs where id=p_planned and pet_id=p_pet for update;if v_id is null then raise exception 'Plan unavailable';end if;end if;
 update public.pet_planned_costs set title=p_data->>'title',category=p_data->>'category',planning_year=y,planned_amount_cents=public.ins_cents(p_data->>'planned_amount_cents'),due_on=public.ins_date(p_data->>'due_on'),appointment_id=nullif(p_data->>'appointment_id','')::uuid,care_plan_id=nullif(p_data->>'care_plan_id','')::uuid,status=coalesce(p_data->>'status','planned'),notes=p_data->>'notes',updated_at=now() where id=v_id;return v_id;end $$;
create function public.convert_planned_cost_to_expense(p_pet uuid,p_planned uuid,p_amount bigint,p_service_date date) returns uuid language plpgsql security definer set search_path='' as $$declare p public.pet_planned_costs;e uuid;begin
 perform public.cost_owner(p_pet,true);select * into p from public.pet_planned_costs where id=p_planned and pet_id=p_pet for update;if p.id is null then raise exception 'Plan unavailable';end if;if p.status='converted_to_expense' then return p.converted_expense_id;end if;if p.status<>'planned' or p_amount is null then raise exception 'Confirm the actual expense amount for an open plan';end if;
 e:=public.save_pet_expense(p_pet,null,jsonb_build_object('title',p.title,'category',p.category,'service_date',p_service_date,'amount_cents',p_amount,'appointment_id',p.appointment_id));update public.pet_planned_costs set status='converted_to_expense',converted_expense_id=e,updated_at=now() where id=p.id;return e;end $$;
create function public.save_pet_cost_budget(p_pet uuid,p_year integer,p_category text,p_amount bigint,p_notes text default null) returns uuid language plpgsql security definer set search_path='' as $$declare h uuid;v_id uuid;begin h:=public.cost_owner(p_pet,true);perform public.cost_year(p_year);insert into public.pet_cost_budgets(household_id,pet_id,created_by,year,category,planned_amount_cents,notes) values(h,p_pet,auth.uid(),p_year,p_category,p_amount,p_notes) on conflict(pet_id,year,category) do update set planned_amount_cents=excluded.planned_amount_cents,notes=excluded.notes,updated_at=now() returning id into v_id;return v_id;end $$;
create function public.cost_expense(p_pet uuid,p_expense uuid) returns public.pet_expenses language plpgsql stable security definer set search_path='' as $$declare e public.pet_expenses;begin perform public.cost_owner(p_pet);select * into e from public.pet_expenses where id=p_expense and pet_id=p_pet;if e.id is null then raise exception 'Expense unavailable';end if;return e;end $$;
create function public.cost_expense_dto(e public.pet_expenses) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('expenseId',e.id,'title',e.title,'category',e.category,'serviceDate',e.service_date,'createdAt',e.created_at,'providerName',e.provider_name,'amountCents',e.amount_cents::text,'allocatedReimbursementCents',a.total::text,'netRecordedCostCents',(e.amount_cents-a.total)::text,'appointmentId',e.appointment_id,'coveragePlanId',e.coverage_plan_id,'source','owner_entered','currency','USD','documentCount',(select count(*) from public.expense_documents where expense_id=e.id and status='ready')) from(select coalesce(sum(allocated_reimbursement_cents),0) total from public.expense_claim_allocations where expense_id=e.id)a$$;
create function public.my_pet_expenses(p_pet uuid,p_year integer,p_category text default null,p_before date default null,p_before_created timestamptz default null,p_before_id uuid default null,p_limit integer default 50) returns jsonb language plpgsql stable security definer set search_path='' as $$declare items jsonb;n integer;begin
 perform public.cost_owner(p_pet);perform public.cost_year(p_year);n:=least(greatest(coalesce(p_limit,50),1),50);
 if (p_before is null) is distinct from (p_before_id is null) or (p_before_created is null) is distinct from (p_before_id is null) then raise exception 'Invalid expense cursor';end if;
 select coalesce(jsonb_agg(public.cost_expense_dto(e) order by e.service_date desc,e.created_at desc,e.id desc),'[]') into items from(select * from public.pet_expenses where pet_id=p_pet and service_date>=make_date(p_year,1,1) and service_date<make_date(p_year+1,1,1) and (p_category is null or category=p_category) and (p_before_id is null or (service_date,created_at,id)<(p_before,p_before_created,p_before_id)) order by service_date desc,created_at desc,id desc limit n+1)e;
 return jsonb_build_object('items',case when jsonb_array_length(items)>n then items-n else items end,'nextCursor',case when jsonb_array_length(items)>n then jsonb_build_object('date',items->(n-1)->>'serviceDate','created',items->(n-1)->>'createdAt','id',items->(n-1)->>'expenseId') else null end);end $$;
create function public.my_pet_expense(p_pet uuid,p_expense uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare e public.pet_expenses;begin e:=public.cost_expense(p_pet,p_expense);return jsonb_build_object('expense',public.cost_expense_dto(e),'notes',e.notes,'allocations',coalesce((select jsonb_agg(jsonb_build_object('claimId',c.id,'title',c.title,'status',c.status,'allocatedCents',a.allocated_reimbursement_cents::text)) from public.expense_claim_allocations a join public.insurance_claims c on c.id=a.claim_id where a.expense_id=e.id),'[]'),'eligibleClaims',coalesce((select jsonb_agg(jsonb_build_object('claimId',c.id,'title',c.title,'status',c.status,'recordedReimbursementCents',c.amount_reimbursed_cents::text,'unallocatedCents',(c.amount_reimbursed_cents-coalesce((select sum(allocated_reimbursement_cents) from public.expense_claim_allocations where claim_id=c.id),0))::text)) from public.insurance_claims c where c.plan_id=e.coverage_plan_id and c.pet_id=e.pet_id),'[]'),'documents',coalesce((select jsonb_agg(jsonb_build_object('id',id,'name',original_filename,'type',document_type,'mime',mime_type,'size',size_bytes,'status',status) order by created_at desc,id) from public.expense_documents where expense_id=e.id and status<>'retired'),'[]'),'events',coalesce((select jsonb_agg(jsonb_build_object('type',event_type,'date',created_at) order by created_at desc,id desc) from(select * from public.pet_expense_events where expense_id=e.id order by created_at desc,id desc limit 100)x),'[]'));end $$;
create function public.cost_planned_dto(p public.pet_planned_costs) returns jsonb language sql immutable set search_path='' as $$select jsonb_build_object('plannedCostId',p.id,'title',p.title,'category',p.category,'plannedAmountCents',p.planned_amount_cents::text,'planningYear',p.planning_year,'dueOn',p.due_on,'status',p.status,'appointmentId',p.appointment_id,'carePlanId',p.care_plan_id,'convertedExpenseId',p.converted_expense_id,'source','owner_entered','notes',p.notes)$$;
create function public.my_pet_planned_costs(p_pet uuid,p_year integer,p_before uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$declare items jsonb;begin perform public.cost_owner(p_pet);perform public.cost_year(p_year);select coalesce(jsonb_agg(public.cost_planned_dto(p) order by p.id desc),'[]') into items from(select * from public.pet_planned_costs where pet_id=p_pet and planning_year=p_year and (p_before is null or id<p_before) order by id desc limit 101)p;return jsonb_build_object('items',case when jsonb_array_length(items)>100 then items-100 else items end,'nextCursor',case when jsonb_array_length(items)>100 then items->99->>'plannedCostId' else null end);end $$;
create function public.my_pet_planned_cost(p_pet uuid,p_planned uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.pet_planned_costs;begin perform public.cost_owner(p_pet);select * into p from public.pet_planned_costs where id=p_planned and pet_id=p_pet;if p.id is null then raise exception 'Plan unavailable';end if;return public.cost_planned_dto(p);end $$;
create function public.my_pet_cost_summary(p_pet uuid,p_year integer) returns jsonb language plpgsql stable security definer set search_path='' as $$declare gross numeric;allocated numeric;planned numeric;b numeric;begin perform public.cost_owner(p_pet);perform public.cost_year(p_year);
 select coalesce(sum(amount_cents),0) into gross from public.pet_expenses where pet_id=p_pet and extract(year from service_date)=p_year;
 select coalesce(sum(a.allocated_reimbursement_cents),0) into allocated from public.expense_claim_allocations a join public.pet_expenses e on e.id=a.expense_id where e.pet_id=p_pet and extract(year from e.service_date)=p_year;
 select coalesce(sum(planned_amount_cents),0) into planned from public.pet_planned_costs where pet_id=p_pet and planning_year=p_year and status='planned';
 select planned_amount_cents into b from public.pet_cost_budgets where pet_id=p_pet and year=p_year and category='all_care';
 return jsonb_build_object('petId',p_pet,'petName',(select name from public.pets where id=p_pet),'year',p_year,'grossExpenses',gross::text,'allocatedReimbursements',allocated::text,'netRecordedCost',(gross-allocated)::text,'plannedUpcoming',planned::text,'budgetAmount',b::text,'remainingRecordedBudget',(b-gross+allocated)::text,'unallocatedAfterRecordedAndPlanned',(b-gross+allocated-planned)::text,'openPlannedCount',(select count(*) from public.pet_planned_costs where pet_id=p_pet and planning_year=p_year and status='planned'),'categoryExpenses',coalesce((select jsonb_agg(jsonb_build_object('category',category,'amountCents',amount::text) order by category) from(select category,sum(amount_cents) amount from public.pet_expenses where pet_id=p_pet and extract(year from service_date)=p_year group by category)c),'[]'),'categoryBudgets',coalesce((select jsonb_agg(jsonb_build_object('category',category,'amountCents',planned_amount_cents::text,'notes',notes) order by category) from public.pet_cost_budgets where pet_id=p_pet and year=p_year),'[]'));end $$;
create function public.my_cost_care_summary(p_year integer) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if auth.uid() is null then raise exception 'Costs unavailable';end if;perform public.cost_year(p_year);return(select coalesce(jsonb_agg(public.my_pet_cost_summary(p.id,p_year) order by p.name,p.id),'[]') from public.pets p join public.households h on h.id=p.household_id where h.owner_id=auth.uid());end $$;
-- Safe choices for explicit owner-created links. No prices, claim identifiers or medical records.
create function public.my_cost_link_options(p_pet uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform public.cost_owner(p_pet);return jsonb_build_object('appointments',coalesce((select jsonb_agg(jsonb_build_object('id',id,'title',title,'date',starts_at)) from(select id,title,starts_at from public.appointments where pet_id=p_pet order by starts_at desc limit 100)a),'[]'),'coveragePlans',coalesce((select jsonb_agg(jsonb_build_object('id',id,'title',carrier_name||case when coverage_kind='wellness_program' then ' — Wellness plan (not insurance)' else '' end)) from public.pet_coverage_plans where pet_id=p_pet),'[]'),'carePlans',coalesce((select jsonb_agg(jsonb_build_object('id',id,'title',title)) from(select id,title from public.care_plans where pet_id=p_pet order by created_at desc limit 100)c),'[]'));end $$;

create function public.prepare_expense_document(p_pet uuid,p_expense uuid,p_name text,p_type text,p_mime text,p_size bigint) returns jsonb language plpgsql security definer set search_path='' as $$declare p public.pet_expenses;d uuid:=gen_random_uuid();path text;begin
 p:=public.cost_expense(p_pet,p_expense);perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('expense-upload:'||auth.uid()::text,0));perform 1 from public.pet_expenses where id=p_expense for update;
 if p_size is null or p_size not between 1 and 10485760 or p_mime is null or not((p_mime='application/pdf' and p_name ~* '\.pdf$') or (p_mime='image/jpeg' and p_name ~* '\.(jpeg|jpg)$') or (p_mime='image/png' and p_name ~* '\.png$')) then raise exception 'Invalid document';end if;
 update public.expense_documents set status='retired' where expense_id=p_expense and status='pending' and created_at<now()-interval '1 hour';
 if (select count(*) from public.expense_documents where expense_id=p_expense and status<>'retired')>=100 or (select count(*) from public.expense_documents where uploaded_by=auth.uid() and created_at>now()-interval '1 day')>=50 then raise exception 'Document limit reached';end if;
 path:='expenses/'||p.household_id||'/'||p.pet_id||'/'||d;
 insert into public.expense_documents(id,expense_id,pet_id,uploaded_by,document_type,original_filename,mime_type,size_bytes,object_path) values(d,p_expense,p_pet,auth.uid(),p_type,p_name,p_mime,p_size,path);return jsonb_build_object('id',d,'path',path);end $$;
create function public.finalize_expense_document(p_document uuid) returns void language plpgsql security definer set search_path='' as $$declare d public.expense_documents;begin
 select * into d from public.expense_documents where id=p_document;if d.id is null then raise exception 'Document unavailable';end if;perform public.cost_expense(d.pet_id,d.expense_id);perform 1 from public.pet_expenses where id=d.expense_id for update;select * into d from public.expense_documents where id=p_document for update;
 if d.status='ready' then return;end if;if d.status<>'pending' or d.created_at<now()-interval '1 hour' then raise exception 'Upload expired';end if;
 if not exists(select 1 from storage.objects where bucket_id='expense-documents' and name=d.object_path and metadata->>'mimetype'=d.mime_type and (metadata->>'size')::bigint=d.size_bytes) then raise exception 'Document missing or invalid';end if;update public.expense_documents set status='ready' where id=d.id;end $$;
create function public.my_expense_document_delivery(p_document uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare d public.expense_documents;begin select * into d from public.expense_documents where id=p_document and status='ready';if d.id is null then raise exception 'Document unavailable';end if;perform public.cost_expense(d.pet_id,d.expense_id);return jsonb_build_object('path',d.object_path,'name',d.original_filename,'mime',d.mime_type,'size',d.size_bytes);end $$;
create function public.can_access_expense_document(p_path text,p_action text) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.expense_documents d join public.pet_expenses p on p.id=d.expense_id join public.households h on h.id=p.household_id where d.object_path=p_path and h.owner_id=auth.uid() and d.pet_id=p.pet_id and ((p_action='read' and d.status='ready') or (p_action='insert' and d.status='pending' and d.created_at>now()-interval '1 hour')))$$;
create function public.retire_expense_document(p_document uuid) returns void language plpgsql security definer set search_path='' as $$declare d public.expense_documents;begin select * into d from public.expense_documents where id=p_document;if d.id is null then raise exception 'Document unavailable';end if;perform public.cost_owner(d.pet_id,true);perform public.cost_expense(d.pet_id,d.expense_id);perform 1 from public.pet_expenses where id=d.expense_id for update;update public.expense_documents set status='retired' where id=d.id and status<>'retired';end $$;
create function public.cost_document_event() returns trigger language plpgsql security definer set search_path='' as $$begin if new.status is distinct from old.status and (new.status='ready' or (new.status='retired' and old.status='ready')) then insert into public.pet_expense_events(expense_id,actor_id,event_type) values(new.expense_id,auth.uid(),case when new.status='ready' then 'document_attached' else 'document_removed' end);end if;return new;end $$;
create trigger cost_document_event after update of status on public.expense_documents for each row execute function public.cost_document_event();
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('expense-documents','expense-documents',false,10485760,array['application/pdf','image/jpeg','image/png']);
create policy expense_document_read on storage.objects for select to authenticated using(bucket_id='expense-documents' and public.can_access_expense_document(name,'read'));
create policy expense_document_insert on storage.objects for insert to authenticated with check(bucket_id='expense-documents' and public.can_access_expense_document(name,'insert'));
create policy expense_document_read_guard on storage.objects as restrictive for select to public using(bucket_id<>'expense-documents' or public.can_access_expense_document(name,'read'));
create policy expense_document_insert_guard on storage.objects as restrictive for insert to public with check(bucket_id<>'expense-documents' or public.can_access_expense_document(name,'insert'));
create policy expense_document_update_guard on storage.objects as restrictive for update to public using(bucket_id<>'expense-documents') with check(bucket_id<>'expense-documents');
create policy expense_document_delete_guard on storage.objects as restrictive for delete to public using(bucket_id<>'expense-documents');

do $$declare t text;f record;begin foreach t in array array['pet_expenses','expense_claim_allocations','pet_expense_events','pet_planned_costs','pet_cost_budgets','expense_documents'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);end loop;
for f in select p.oid::regprocedure sig,p.proname name from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (left(p.proname,5)='cost_' or p.proname in ('save_pet_expense','set_expense_claim_allocation','save_pet_planned_cost','convert_planned_cost_to_expense','save_pet_cost_budget','my_pet_expenses','my_pet_expense','my_pet_planned_costs','my_pet_planned_cost','my_pet_cost_summary','my_cost_care_summary','my_cost_link_options','prepare_expense_document','finalize_expense_document','retire_expense_document','my_expense_document_delivery','can_access_expense_document')) loop execute format('revoke all on function %s from public,anon,authenticated',f.sig);if left(f.name,5)<>'cost_' then execute format('grant execute on function %s to authenticated',f.sig);end if;end loop;end $$;
-- This boolean returns false for anon, but must be executable for other buckets' public reads.
grant execute on function public.can_access_expense_document(text,text) to anon;
commit;
